package com.novacommerce.inventory.integration;
import static org.assertj.core.api.Assertions.*; import com.novacommerce.inventory.api.dto.InventoryRequests.*; import com.novacommerce.inventory.application.InventoryService; import com.novacommerce.inventory.domain.inventory.InventoryItem; import com.novacommerce.inventory.infrastructure.persistence.*; import java.time.Instant; import java.util.*; import java.util.concurrent.*; import java.util.concurrent.atomic.AtomicInteger; import org.flywaydb.core.Flyway; import org.junit.jupiter.api.*; import org.springframework.beans.factory.annotation.Autowired; import org.springframework.boot.test.context.SpringBootTest; import org.springframework.jdbc.core.JdbcTemplate; import org.springframework.test.context.DynamicPropertyRegistry; import org.springframework.test.context.DynamicPropertySource; import org.testcontainers.junit.jupiter.*; import org.testcontainers.postgresql.PostgreSQLContainer;
@SpringBootTest @Testcontainers(disabledWithoutDocker=true) class InventoryPostgresIntegrationTests {
 @Container static final PostgreSQLContainer postgres=new PostgreSQLContainer("postgres:17.5-alpine");
 @DynamicPropertySource static void properties(DynamicPropertyRegistry r){r.add("spring.datasource.url",postgres::getJdbcUrl);r.add("spring.datasource.username",postgres::getUsername);r.add("spring.datasource.password",postgres::getPassword);r.add("inventory.auth.issuer",()->"test");r.add("inventory.auth.audience",()->"test");r.add("inventory.auth.jwks-uri",()->"http://127.0.0.1:1");r.add("inventory.expiration-scan-interval",()->"PT1H");}
 @Autowired InventoryService service;@Autowired InventoryItemRepository items;@Autowired InventoryReservationRepository reservations;@Autowired JdbcTemplate jdbc;@Autowired Flyway flyway;
 @BeforeEach void clear(){reservations.deleteAll();items.deleteAll();}
 @Test void preventsOversellingUnderOneHundredConcurrentTransactions()throws Exception{UUID id=UUID.randomUUID();items.save(new InventoryItem(id,10,Instant.now()));int attempts=100;ExecutorService pool=Executors.newFixedThreadPool(attempts);CountDownLatch ready=new CountDownLatch(attempts),start=new CountDownLatch(1);AtomicInteger success=new AtomicInteger(),insufficient=new AtomicInteger();List<Future<?>> futures=new ArrayList<>();for(int n=0;n<attempts;n++){String key="concurrent-"+n;futures.add(pool.submit(()->{ready.countDown();try{start.await();service.reserve(key,new ReservationRequest(List.of(new ReservationLine(id,1))),UUID.randomUUID());success.incrementAndGet();}catch(com.novacommerce.inventory.domain.inventory.InsufficientStockException e){insufficient.incrementAndGet();}catch(InterruptedException e){Thread.currentThread().interrupt();}}));}ready.await();start.countDown();for(Future<?> f:futures)f.get(30,TimeUnit.SECONDS);pool.shutdown();InventoryItem finalItem=items.findById(id).orElseThrow();assertThat(success).hasValue(10);assertThat(insufficient).hasValue(90);assertThat(finalItem.getReserved()).isEqualTo(10);assertThat(finalItem.available()).isZero();assertThat(finalItem.getReserved()).isLessThanOrEqualTo(finalItem.getOnHand());}
 @Test void multiItemFailureIsAtomicAndIdempotencyDoesNotReserveTwice(){UUID a=UUID.randomUUID(),b=UUID.randomUUID(),owner=UUID.randomUUID();items.saveAll(List.of(new InventoryItem(a,10,Instant.now()),new InventoryItem(b,0,Instant.now())));assertThatThrownBy(()->service.reserve("atomic",new ReservationRequest(List.of(new ReservationLine(a,2),new ReservationLine(b,1))),owner)).isInstanceOf(com.novacommerce.inventory.domain.inventory.InsufficientStockException.class);assertThat(items.findById(a).orElseThrow().getReserved()).isZero();items.deleteById(b);var request=new ReservationRequest(List.of(new ReservationLine(a,2)));var first=service.reserve("same",request,owner);var replay=service.reserve("same",request,owner);assertThat(replay.reservation().id()).isEqualTo(first.reservation().id());assertThat(items.findById(a).orElseThrow().getReserved()).isEqualTo(2);assertThatThrownBy(()->service.reserve("same",new ReservationRequest(List.of(new ReservationLine(a,3))),owner)).hasMessageContaining("Idempotency");}
 @Test void migrationsConstraintsReleaseAndCommitWork(){assertThat(flyway.info().current().getVersion().getVersion()).isEqualTo("2");UUID releaseId=UUID.randomUUID(),commitId=UUID.randomUUID(),owner=UUID.randomUUID();items.saveAll(List.of(new InventoryItem(releaseId,10,Instant.now()),new InventoryItem(commitId,10,Instant.now())));var released=service.reserve("release",new ReservationRequest(List.of(new ReservationLine(releaseId,3))),owner).reservation();service.release(released.id(),owner,false);assertThat(items.findById(releaseId).orElseThrow().getReserved()).isZero();var committed=service.reserve("commit",new ReservationRequest(List.of(new ReservationLine(commitId,3))),owner).reservation();service.commit(committed.id());InventoryItem consumed=items.findById(commitId).orElseThrow();assertThat(consumed.getOnHand()).isEqualTo(7);assertThat(consumed.getReserved()).isZero();UUID invalid=UUID.randomUUID();assertThatThrownBy(()->jdbc.update("insert into inventory_items(variant_id,on_hand,reserved,version,created_at,updated_at) values (?,1,2,0,now(),now())",invalid)).isInstanceOf(Exception.class);}
 @Test void concurrentSameKeyCreatesOneLogicalReservation()throws Exception{UUID id=UUID.randomUUID(),owner=UUID.randomUUID();items.save(new InventoryItem(id,10,Instant.now()));var request=new ReservationRequest(List.of(new ReservationLine(id,2)));ExecutorService pool=Executors.newFixedThreadPool(2);CountDownLatch start=new CountDownLatch(1);Callable<UUID> call=()->{start.await();return service.reserve("shared-key",request,owner).reservation().id();};Future<UUID> first=pool.submit(call),second=pool.submit(call);start.countDown();assertThat(first.get(10,TimeUnit.SECONDS)).isEqualTo(second.get(10,TimeUnit.SECONDS));pool.shutdown();assertThat(reservations.count()).isEqualTo(1);assertThat(items.findById(id).orElseThrow().getReserved()).isEqualTo(2);}
}
