package com.novacommerce.inventory.integration;
import static org.springframework.security.test.web.servlet.request.SecurityMockMvcRequestPostProcessors.csrf; import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post; import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;
import com.nimbusds.jose.*; import com.nimbusds.jose.crypto.RSASSASigner; import com.nimbusds.jose.jwk.*; import com.nimbusds.jwt.*; import com.sun.net.httpserver.HttpServer; import jakarta.servlet.http.Cookie; import java.net.*; import java.nio.charset.StandardCharsets; import java.security.KeyPair; import java.security.KeyPairGenerator; import java.security.interfaces.RSAPrivateKey; import java.security.interfaces.RSAPublicKey; import java.time.Instant; import java.util.*; import org.junit.jupiter.api.*; import org.springframework.beans.factory.annotation.Autowired; import org.springframework.boot.test.context.SpringBootTest; import org.springframework.boot.webmvc.test.autoconfigure.AutoConfigureMockMvc; import org.springframework.http.MediaType; import org.springframework.test.context.*; import org.springframework.test.web.servlet.MockMvc;
@SpringBootTest @AutoConfigureMockMvc @ActiveProfiles("test") class InventoryJwtJwksIntegrationTests {static final String KID="inventory-test-key";static final RSAKey KEY=key();static final HttpServer SERVER=server();@Autowired MockMvc mvc;
 @DynamicPropertySource static void props(DynamicPropertyRegistry r){r.add("inventory.auth.jwks-uri",()->"http://127.0.0.1:"+SERVER.getAddress().getPort()+"/jwks");}
 @AfterAll static void stop(){SERVER.stop(0);}
 @Test void validatesRealCookieJwtRoleAndCsrf()throws Exception{UUID id=UUID.randomUUID();String body="{\"quantityDelta\":5,\"reason\":\"signed admin\"}";Cookie admin=new Cookie("NC_ACCESS",token("ADMIN"));mvc.perform(post("/api/v1/admin/inventory/{id}/adjustments",id).cookie(admin).contentType(MediaType.APPLICATION_JSON).content(body)).andExpect(status().isForbidden());mvc.perform(post("/api/v1/admin/inventory/{id}/adjustments",id).cookie(admin).with(csrf()).contentType(MediaType.APPLICATION_JSON).content(body)).andExpect(status().isOk());}
 static String token(String role)throws Exception{Instant now=Instant.now();SignedJWT jwt=new SignedJWT(new JWSHeader.Builder(JWSAlgorithm.RS256).keyID(KID).build(),new JWTClaimsSet.Builder().issuer("test-issuer").audience("test-audience").subject(UUID.randomUUID().toString()).issueTime(Date.from(now)).expirationTime(Date.from(now.plusSeconds(300))).claim("roles",List.of(role)).build());jwt.sign(new RSASSASigner(KEY.toRSAPrivateKey()));return jwt.serialize();}
 static RSAKey key(){try{KeyPairGenerator g=KeyPairGenerator.getInstance("RSA");g.initialize(2048);KeyPair p=g.generateKeyPair();return new RSAKey.Builder((RSAPublicKey)p.getPublic()).privateKey((RSAPrivateKey)p.getPrivate()).keyID(KID).build();}catch(Exception e){throw new IllegalStateException(e);}}
 static HttpServer server(){try{HttpServer s=HttpServer.create(new InetSocketAddress("127.0.0.1",0),0);s.createContext("/jwks",x->{byte[] b=new JWKSet(KEY.toPublicJWK()).toString().getBytes(StandardCharsets.UTF_8);x.sendResponseHeaders(200,b.length);x.getResponseBody().write(b);x.close();});s.start();return s;}catch(Exception e){throw new IllegalStateException(e);}}
}
