package com.novacommerce.inventory.config;
import com.novacommerce.inventory.infrastructure.security.CookieBearerTokenResolver; import jakarta.servlet.http.HttpServletResponse; import java.io.IOException; import java.time.Instant; import java.util.List;
import org.springframework.beans.factory.annotation.Qualifier; import org.springframework.context.annotation.*; import org.springframework.http.*; import org.springframework.security.authentication.ProviderManager; import org.springframework.security.config.annotation.web.builders.HttpSecurity; import org.springframework.security.config.annotation.web.configuration.EnableWebSecurity; import org.springframework.security.config.http.SessionCreationPolicy; import org.springframework.security.oauth2.core.*; import org.springframework.security.oauth2.jwt.*; import org.springframework.security.oauth2.server.resource.authentication.*; import org.springframework.security.oauth2.server.resource.web.authentication.BearerTokenAuthenticationFilter; import org.springframework.security.web.*; import org.springframework.security.web.authentication.*; import org.springframework.security.web.csrf.CookieCsrfTokenRepository; import org.springframework.security.web.util.matcher.RequestMatcher; import org.springframework.web.cors.*;
@Configuration @EnableWebSecurity
public class SecurityConfig {
 @Bean JwtDecoder inventoryJwtDecoder(InventoryProperties p){NimbusJwtDecoder d=NimbusJwtDecoder.withJwkSetUri(p.getAuth().getJwksUri()).build();d.setJwtValidator(new DelegatingOAuth2TokenValidator<>(JwtValidators.createDefaultWithIssuer(p.getAuth().getIssuer()),new AudienceValidator(p.getAuth().getAudience())));return d;}
 @Bean JwtAuthenticationConverter inventoryJwtAuthenticationConverter(){JwtGrantedAuthoritiesConverter r=new JwtGrantedAuthoritiesConverter();r.setAuthoritiesClaimName("roles");r.setAuthorityPrefix("ROLE_");JwtAuthenticationConverter c=new JwtAuthenticationConverter();c.setJwtGrantedAuthoritiesConverter(r);return c;}
 @Bean SecurityFilterChain inventorySecurityFilterChain(HttpSecurity http,CookieBearerTokenResolver resolver,JwtDecoder decoder,JwtAuthenticationConverter converter,@Qualifier("inventoryCors") CorsConfigurationSource cors)throws Exception{
  CookieCsrfTokenRepository csrf=CookieCsrfTokenRepository.withHttpOnlyFalse();csrf.setCookieCustomizer(b->b.sameSite("Lax").path("/"));RequestMatcher mutations=r->!List.of("GET","HEAD","TRACE","OPTIONS").contains(r.getMethod())&&r.getRequestURI().startsWith("/api/");
  JwtAuthenticationProvider provider=new JwtAuthenticationProvider(decoder);provider.setJwtAuthenticationConverter(converter);BearerTokenAuthenticationFilter filter=new BearerTokenAuthenticationFilter(new ProviderManager(provider),request->{String token=resolver.resolve(request);return token==null?null:new BearerTokenAuthenticationToken(token);});filter.setAuthenticationEntryPoint((q,s,e)->write(s,HttpStatus.UNAUTHORIZED,"AUTHENTICATION_REQUIRED","Authentication required",q.getRequestURI()));
  http.csrf(c->c.csrfTokenRepository(csrf).requireCsrfProtectionMatcher(mutations)).cors(c->c.configurationSource(cors)).sessionManagement(c->c.sessionCreationPolicy(SessionCreationPolicy.STATELESS)).authorizeHttpRequests(a->a
   .requestMatchers("/actuator/health","/api/v1/inventory/csrf").permitAll()
   .requestMatchers(HttpMethod.GET,"/api/v1/inventory/variants/**").permitAll()
   .requestMatchers(HttpMethod.POST,"/api/v1/inventory/availability").permitAll()
   .requestMatchers("/api/v1/admin/inventory/**").hasRole("ADMIN")
   .requestMatchers("/api/v1/inventory/reservations/**").hasAnyRole("CUSTOMER","ADMIN").anyRequest().denyAll())
   .addFilterBefore(filter,AnonymousAuthenticationFilter.class).exceptionHandling(e->e.authenticationEntryPoint((q,s,x)->write(s,HttpStatus.UNAUTHORIZED,"AUTHENTICATION_REQUIRED","Authentication required",q.getRequestURI())).accessDeniedHandler((q,s,x)->write(s,HttpStatus.FORBIDDEN,"ACCESS_DENIED","Access denied",q.getRequestURI())));return http.build();
 }
 @Bean(name="inventoryCors") CorsConfigurationSource inventoryCors(InventoryProperties p){CorsConfiguration c=new CorsConfiguration();c.setAllowedOrigins(p.getAllowedOrigins());c.setAllowedMethods(List.of("GET","POST","OPTIONS"));c.setAllowedHeaders(List.of("Content-Type","X-XSRF-TOKEN","Idempotency-Key"));c.setAllowCredentials(true);UrlBasedCorsConfigurationSource s=new UrlBasedCorsConfigurationSource();s.registerCorsConfiguration("/api/**",c);return s;}
 private static void write(HttpServletResponse r,HttpStatus s,String code,String message,String path)throws IOException{r.setStatus(s.value());r.setContentType(MediaType.APPLICATION_JSON_VALUE);r.getWriter().write("{\"timestamp\":\""+Instant.now()+"\",\"status\":"+s.value()+",\"code\":\""+code+"\",\"message\":\""+message+"\",\"path\":\""+path+"\"}");}
}
