package com.novacommerce.inventory.domain.inventory;
public enum MovementType { INITIAL_STOCK, RESTOCK, CORRECTION_INCREASE, CORRECTION_DECREASE, RESERVATION_CREATED, RESERVATION_RELEASED, RESERVATION_EXPIRED, RESERVATION_COMMITTED }
