"use client";

import Link from "next/link";
import { useRouter, useSearchParams } from "next/navigation";
import { FormEvent, useEffect, useState } from "react";
import { Brand, Category, ProductPage, getBrands, getCategories, getProducts } from "@/lib/catalog-client";

export default function ProductDiscovery() {
  const router = useRouter(); const search = useSearchParams();
  const [data, setData] = useState<ProductPage | null>(null); const [categories, setCategories] = useState<Category[]>([]); const [brands, setBrands] = useState<Brand[]>([]); const [error, setError] = useState<string | null>(null); const [loading, setLoading] = useState(true);
  const [q, setQ] = useState(search.get("q") ?? ""); const [category, setCategory] = useState(search.get("category") ?? ""); const [brand, setBrand] = useState(search.get("brand") ?? ""); const [sort, setSort] = useState(search.get("sort") ?? "newest");
  useEffect(() => { Promise.all([getCategories(), getBrands()]).then(([c, b]) => { setCategories(c); setBrands(b); }).catch(() => undefined); }, []);
  useEffect(() => { setLoading(true); setError(null); getProducts(new URLSearchParams(search.toString())).then(setData).catch(() => setError("Catalog is unavailable. Start catalog-service and try again.")).finally(() => setLoading(false)); }, [search]);
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const params = new URLSearchParams(); if (q) params.set("q", q); if (category) params.set("category", category); if (brand) params.set("brand", brand); if (sort) params.set("sort", sort); params.set("page", "0"); params.set("size", "12"); router.push(`/products?${params.toString()}`); }
  function page(page: number) { const params = new URLSearchParams(search.toString()); params.set("page", String(page)); router.push(`/products?${params.toString()}`); }
  return <main className="shell storefront"><header className="topbar"><Link className="brand" href="/">NovaCommerce</Link><nav><Link className="health-link" href="/">Platform</Link><span aria-hidden="true"> · </span><Link className="health-link" href="/health">Health</Link></nav></header><section className="store-heading"><p className="eyebrow">Storefront foundation</p><h1>Product discovery</h1><p className="intro">A real catalog surface backed by the Catalog Service. Inventory and checkout arrive in later phases.</p></section><form className="filters" onSubmit={submit}><label>Search<input value={q} onChange={(e) => setQ(e.target.value)} placeholder="Search products" /></label><label>Category<select value={category} onChange={(e) => setCategory(e.target.value)}><option value="">All categories</option>{categories.map((item) => <option key={item.id} value={item.slug}>{item.name}</option>)}</select></label><label>Brand<select value={brand} onChange={(e) => setBrand(e.target.value)}><option value="">All brands</option>{brands.map((item) => <option key={item.id} value={item.slug}>{item.name}</option>)}</select></label><label>Sort<select value={sort} onChange={(e) => setSort(e.target.value)}><option value="newest">Newest</option><option value="relevance">Relevance</option><option value="price_asc">Price: low to high</option><option value="price_desc">Price: high to low</option></select></label><button type="submit">Apply filters</button></form>{loading && <p role="status" className="form-copy">Loading catalog…</p>}{error && <p role="alert" className="form-error">{error}</p>}{!loading && !error && data?.items.length === 0 && <p className="form-copy">No products match these filters.</p>}<div className="product-grid">{data?.items.map((product) => <Link className="product-card" href={`/products/${product.slug}`} key={product.id}><span className="card-status">{product.brand?.name ?? "NovaCommerce catalog"}</span><h2>{product.name}</h2><p>{product.shortDescription ?? "Product details available in the catalog."}</p>{product.startingPrice && <strong>{product.startingPrice.amount} {product.startingPrice.currency}</strong>}</Link>)}</div>{data && data.totalPages > 1 && <nav className="pagination" aria-label="Catalog pages"><button disabled={data.page === 0} onClick={() => page(data.page - 1)}>Previous</button><span>Page {data.page + 1} of {data.totalPages}</span><button disabled={data.page + 1 >= data.totalPages} onClick={() => page(data.page + 1)}>Next</button></nav>}</main>;
}
