package com.novacommerce.inventory.api.error;
import com.novacommerce.inventory.domain.inventory.*; import jakarta.servlet.http.HttpServletRequest; import java.time.Instant; import java.util.*; import org.springframework.dao.*; import org.springframework.http.*; import org.springframework.orm.*; import org.springframework.web.bind.MethodArgumentNotValidException; import org.springframework.web.bind.annotation.*;
@RestControllerAdvice public class InventoryExceptionHandler {
 @ExceptionHandler(InventoryException.class) ResponseEntity<InventoryApiError> inventory(InventoryException e,HttpServletRequest r){return body(e.getStatus(),e.getCode(),e.getMessage(),r,Map.of());}
 @ExceptionHandler(InsufficientStockException.class) ResponseEntity<InventoryApiError> stock(InsufficientStockException e,HttpServletRequest r){return body(HttpStatus.CONFLICT,"INSUFFICIENT_STOCK",e.getMessage(),r,Map.of());}
 @ExceptionHandler(StockAdjustmentConflictException.class) ResponseEntity<InventoryApiError> adjust(StockAdjustmentConflictException e,HttpServletRequest r){return body(HttpStatus.CONFLICT,"STOCK_ADJUSTMENT_CONFLICT",e.getMessage(),r,Map.of());}
 @ExceptionHandler(MethodArgumentNotValidException.class) ResponseEntity<InventoryApiError> validation(MethodArgumentNotValidException e,HttpServletRequest r){Map<String,String> f=new LinkedHashMap<>();e.getBindingResult().getFieldErrors().forEach(x->f.putIfAbsent(x.getField(),x.getDefaultMessage()));return body(HttpStatus.BAD_REQUEST,"VALIDATION_FAILED","Request validation failed",r,f);}
 @ExceptionHandler(IllegalArgumentException.class) ResponseEntity<InventoryApiError> illegal(IllegalArgumentException e,HttpServletRequest r){return body(HttpStatus.BAD_REQUEST,"VALIDATION_FAILED",e.getMessage(),r,Map.of());}
 @ExceptionHandler({CannotAcquireLockException.class,PessimisticLockingFailureException.class,ObjectOptimisticLockingFailureException.class}) ResponseEntity<InventoryApiError> concurrent(Exception e,HttpServletRequest r){return body(HttpStatus.CONFLICT,"CONCURRENT_MODIFICATION","Inventory changed concurrently; retry safely",r,Map.of());}
 @ExceptionHandler(DataIntegrityViolationException.class) ResponseEntity<InventoryApiError> integrity(Exception e,HttpServletRequest r){return body(HttpStatus.CONFLICT,"CONCURRENT_MODIFICATION","Inventory constraint rejected the operation",r,Map.of());}
 private ResponseEntity<InventoryApiError> body(HttpStatus s,String c,String m,HttpServletRequest r,Map<String,String> f){return ResponseEntity.status(s).body(new InventoryApiError(Instant.now(),s.value(),c,m,r.getRequestURI(),f));}
}
