ALTER TABLE orders DROP CONSTRAINT IF EXISTS order_status;
ALTER TABLE orders ADD CONSTRAINT order_status CHECK (status IN ('PENDING_INVENTORY', 'AWAITING_PAYMENT', 'CONFIRMED', 'PAYMENT_FAILED', 'CANCELLED', 'EXPIRED'));
