package com.novacommerce.inventory.application;
import com.novacommerce.inventory.api.dto.InventoryDtos; import com.novacommerce.inventory.api.dto.InventoryDtos.Availability; import com.novacommerce.inventory.api.dto.InventoryDtos.AdminInventory; import com.novacommerce.inventory.api.dto.InventoryDtos.Movement; import com.novacommerce.inventory.api.dto.InventoryDtos.Reservation; import com.novacommerce.inventory.api.dto.InventoryRequests.ReservationRequest; import com.novacommerce.inventory.api.dto.InventoryRequests.ReservationLine; import com.novacommerce.inventory.api.error.InventoryException; import com.novacommerce.inventory.config.InventoryProperties; import com.novacommerce.inventory.domain.inventory.*; import com.novacommerce.inventory.domain.reservation.*; import com.novacommerce.inventory.infrastructure.persistence.*;
import io.micrometer.core.instrument.MeterRegistry; import java.time.*; import java.util.*; import java.util.function.Consumer; import org.springframework.data.domain.PageRequest; import org.springframework.http.HttpStatus; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.*;
@Service public class InventoryService {
 private final InventoryItemRepository inventories;private final InventoryReservationRepository reservations;private final InventoryMovementRepository movements;private final IdempotencyKeyLock keyLock;private final ReservationRequestHasher hasher;private final InventoryProperties properties;private final Clock clock;private final MeterRegistry metrics;
 public InventoryService(InventoryItemRepository i,InventoryReservationRepository r,InventoryMovementRepository m,IdempotencyKeyLock k,ReservationRequestHasher h,InventoryProperties p,Clock c,MeterRegistry metrics){inventories=i;reservations=r;movements=m;keyLock=k;hasher=h;properties=p;clock=c;this.metrics=metrics;}
 @Transactional(readOnly=true) public Availability availability(UUID id){return InventoryDtos.availability(inventories.findById(id).orElseThrow(()->error(HttpStatus.NOT_FOUND,"INVENTORY_NOT_FOUND","Inventory not found")));}
 @Transactional(readOnly=true) public List<Availability> availability(Set<UUID> ids){Map<UUID,InventoryItem> found=new HashMap<>();inventories.findAllByVariantIdIn(ids).forEach(i->found.put(i.getVariantId(),i));return ids.stream().sorted().map(id->{InventoryItem i=found.get(id);return i==null?new Availability(id,"OUT_OF_STOCK",0):InventoryDtos.availability(i);}).toList();}
 @Transactional public AdminInventory adjust(UUID id,long delta,String reason,UUID actor){Instant now=clock.instant();Optional<InventoryItem> existing=inventories.lockAllOrdered(List.of(id)).stream().findFirst();if(existing.isEmpty()&&delta<0)throw error(HttpStatus.NOT_FOUND,"INVENTORY_NOT_FOUND","Inventory not found");InventoryItem item=existing.orElseGet(()->new InventoryItem(id,0,now));item.adjust(delta,now);inventories.save(item);MovementType type=existing.isEmpty()?MovementType.INITIAL_STOCK:delta>0?MovementType.RESTOCK:MovementType.CORRECTION_DECREASE;movements.save(new InventoryMovement(id,type,delta,0,null,reason,actor,now));metrics.counter("inventory.adjustments").increment();return InventoryDtos.admin(item);}
 @Transactional(readOnly=true) public AdminInventory admin(UUID id){return InventoryDtos.admin(inventories.findById(id).orElseThrow(()->error(HttpStatus.NOT_FOUND,"INVENTORY_NOT_FOUND","Inventory not found")));}
 @Transactional(readOnly=true) public List<Movement> movements(UUID id){if(!inventories.existsById(id))throw error(HttpStatus.NOT_FOUND,"INVENTORY_NOT_FOUND","Inventory not found");return movements.findByVariantIdOrderByCreatedAtDesc(id,PageRequest.of(0,100)).stream().map(InventoryDtos::movement).toList();}
 @Transactional public CreationResult reserve(String key,ReservationRequest request,UUID owner){if(key==null||key.isBlank())throw error(HttpStatus.BAD_REQUEST,"IDEMPOTENCY_KEY_REQUIRED","Idempotency-Key header is required");if(key.length()>200)throw error(HttpStatus.BAD_REQUEST,"VALIDATION_FAILED","Idempotency-Key is too long");ensureUnique(request.items());String hash=hasher.hash(request.items());keyLock.acquire(key);Optional<InventoryReservation> prior=reservations.findByIdempotencyKey(key);if(prior.isPresent()){if(!prior.get().getRequestHash().equals(hash))throw error(HttpStatus.CONFLICT,"IDEMPOTENCY_KEY_REUSED","Idempotency key was used for another request");return new CreationResult(InventoryDtos.reservation(prior.get()),false);}
  Instant now=clock.instant();List<UUID> ids=request.items().stream().map(ReservationLine::variantId).sorted().toList();Map<UUID,InventoryItem> locked=new LinkedHashMap<>();inventories.lockAllOrdered(ids).forEach(i->locked.put(i.getVariantId(),i));if(locked.size()!=ids.size())throw error(HttpStatus.NOT_FOUND,"INVENTORY_NOT_FOUND","Inventory not found for one or more variants");
  InventoryReservation reservation=new InventoryReservation(UUID.randomUUID(),key,hash,owner,now.plus(properties.getReservationTtl()),now,request.items().stream().map(i->new ReservationItem(i.variantId(),i.quantity())).toList());
  for(ReservationLine line:request.items().stream().sorted(Comparator.comparing(ReservationLine::variantId)).toList()){InventoryItem item=locked.get(line.variantId());item.reserve(line.quantity(),now);movements.save(new InventoryMovement(line.variantId(),MovementType.RESERVATION_CREATED,0,line.quantity(),reservation.getId(),null,owner,now));}
  inventories.saveAll(locked.values());reservations.save(reservation);metrics.counter("inventory.reservations.created").increment();return new CreationResult(InventoryDtos.reservation(reservation),true);
 }
 @Transactional(readOnly=true) public Reservation get(UUID id,UUID subject,boolean admin){InventoryReservation r=reservations.findById(id).orElseThrow(()->error(HttpStatus.NOT_FOUND,"RESERVATION_NOT_FOUND","Reservation not found"));authorize(r,subject,admin);return InventoryDtos.reservation(r);}
 @Transactional public Reservation release(UUID id,UUID subject,boolean admin){return transition(id,subject,admin,false);}
 @Transactional public Reservation commit(UUID id){return transition(id,null,true,true);}
 private Reservation transition(UUID id,UUID subject,boolean admin,boolean commit){InventoryReservation r=reservations.lockById(id).orElseThrow(()->error(HttpStatus.NOT_FOUND,"RESERVATION_NOT_FOUND","Reservation not found"));authorize(r,subject,admin);if((commit&&r.getStatus()==ReservationStatus.COMMITTED)||(!commit&&r.getStatus()==ReservationStatus.RELEASED))return InventoryDtos.reservation(r);if(!commit&&r.getStatus()==ReservationStatus.COMMITTED)throw error(HttpStatus.CONFLICT,"RESERVATION_ALREADY_COMMITTED","Committed reservation cannot be released");if(r.getStatus()!=ReservationStatus.ACTIVE)throw error(HttpStatus.CONFLICT,r.getStatus()==ReservationStatus.EXPIRED?"RESERVATION_EXPIRED":"INVALID_RESERVATION_STATE","Reservation is not active");Instant now=clock.instant();List<InventoryItem> locked=inventories.lockAllOrdered(r.getItems().stream().map(ReservationItem::getVariantId).sorted().toList());Map<UUID,InventoryItem> byId=new HashMap<>();locked.forEach(i->byId.put(i.getVariantId(),i));Consumer<ReservationItem> action=line->{InventoryItem item=byId.get(line.getVariantId());if(commit)item.commit(line.getQuantity(),now);else item.release(line.getQuantity(),now);movements.save(new InventoryMovement(line.getVariantId(),commit?MovementType.RESERVATION_COMMITTED:MovementType.RESERVATION_RELEASED,commit?-line.getQuantity():0,-line.getQuantity(),r.getId(),null,subject,now));};r.getItems().stream().sorted(Comparator.comparing(ReservationItem::getVariantId)).forEach(action);if(commit)r.commit(now);else r.release(now);return InventoryDtos.reservation(r);}
 @Transactional public int expireBatch(){Instant now=clock.instant();List<UUID> ids=reservations.claimExpired(now,properties.getExpirationBatchSize());for(UUID id:ids)expireLocked(id,now);if(!ids.isEmpty())metrics.counter("inventory.reservations.expired").increment(ids.size());return ids.size();}
 private void expireLocked(UUID id,Instant now){InventoryReservation r=reservations.lockById(id).orElseThrow();if(r.getStatus()!=ReservationStatus.ACTIVE||r.getExpiresAt().isAfter(now))return;Map<UUID,InventoryItem> items=new HashMap<>();inventories.lockAllOrdered(r.getItems().stream().map(ReservationItem::getVariantId).sorted().toList()).forEach(i->items.put(i.getVariantId(),i));for(ReservationItem line:r.getItems()){items.get(line.getVariantId()).release(line.getQuantity(),now);movements.save(new InventoryMovement(line.getVariantId(),MovementType.RESERVATION_EXPIRED,0,-line.getQuantity(),r.getId(),null,null,now));}r.expire(now);}
 private static void ensureUnique(List<ReservationLine> lines){Set<UUID> ids=new HashSet<>();for(ReservationLine line:lines)if(!ids.add(line.variantId()))throw error(HttpStatus.BAD_REQUEST,"VALIDATION_FAILED","Duplicate variant IDs are not allowed");}
 private static void authorize(InventoryReservation r,UUID subject,boolean admin){if(!admin&&!Objects.equals(r.getOwnerId(),subject))throw error(HttpStatus.FORBIDDEN,"RESERVATION_ACCESS_DENIED","Reservation belongs to another customer");}
 private static InventoryException error(HttpStatus s,String c,String m){return new InventoryException(s,c,m);} public record CreationResult(Reservation reservation,boolean created){}
}
